name: Auction Scraper Automation

on:
  schedule:
    - cron: '0 0 */2 * *'  # Every 48 hours at midnight UTC
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hour timeout
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python main.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: scraper-logs
        path: |
          *.log
          logs/
