name: Auction Scraper Automation

on:
  schedule:
    # Runs every 48 hours (at 00:00 UTC)
    - cron: '0 0 */2 * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run scraper
      env:
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
      run: python main.py
      
    - name: Commit and push changes if any
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')" && git push)
        
