name: Auction Scraper Automation

on:
  schedule:
  - cron: '0 0 */2 * *'  
  workflow_dispatch:  # Still allows manual runs via GitHub UI
  
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 3 hour timeout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # Log installed packages for debugging

      - name: Run scraper
        run: python main.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraper-logs
          path: |
            *.log
            logs/
