name: Auction Scraper

on:
  schedule:
    - cron: '0 0 */2 * *'  # Runs every 48 hours at midnight UTC (5:00 AM PKT)
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager gspread oauth2client

      - name: Set up Google Sheets credentials
        run: |
          echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > credentials.json

      - name: Run scraper
        run: python main.py

      - name: Clean up
        run: rm credentials.json
        if: always()
